title: My Website
baseurl: ""


collections:
  writings:
    output: true
    permalink: /projects/:name/
  projects:
    output: true
    permalink: /publications/:name/
  puzzles:
    output: true
    permalink: /puzzles/:name/